server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jihyunhillpark/spring-cloud-practice-repo.git
          default-label: main
          search-paths: e-commerce-practice
