server:
  port: 8888
spring:
  application:
    name: config-service
  #  profiles:
  #    active: native
  cloud:
    config:
      server:
        #        native:
        #          search-locations: file://${user.home}/personal_proj/spring-cloud-practice-repo/e-commerce-practice
        git:
          uri: https://github.com/jihyunhillpark/spring-cloud-practice-repo.git
          default-label: main
          search-paths: e-commerce-practice
